version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: standard
        filename: info.log
        #maxBytes: 10485760 # 10MB
        backupCount: 20
        when: D
        interval: 1
        encoding: utf8

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: ERROR
        formatter: error
        filename: errors.log
        #maxBytes: 10485760 # 10MB
        backupCount: 20
        when: D
        interval: 1
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: debug.log
        #maxBytes: 10485760 # 10MB
        backupCount: 40
        when: H
        interval: 6
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: critical.log
        #maxBytes: 10485760 # 10MB
        backupCount: 20
        when: D
        interval: 1
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: WARN
        formatter: standard
        filename: warn.log
        #maxBytes: 10485760 # 10MB
        backupCount: 20
        when: D
        interval: 1
        encoding: utf8

root:
    level: INFO
    handlers: [console]
    propogate: yes

loggers:
    nww_oi_muc:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes

    nww_oi_muc_bot:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes

    nww_oi_ldm_encoder:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes

    nww_oi_muc_slibot:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes
        
    nww_oi_rate:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes
        
    slixmpp:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes
        
    xmlstream:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes
